### ISSUE TITLE
[QZ 0] : build.gradle file, difference between testImplementation and testCompile?

### ISSUE THREAD

**Issue by leahsidoniesmith** [emory-courses/dsa-java#18]
I am confident that my code compiles properly, but I did notice a slight difference between my code in the "build.gradle" file and the professor's code.

Professor's code:
```
dependencies {
    testImplementation 'junit:junit:4.13'
}
```
My code:
```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```
I am wondering about the difference between testImplementation and testCompile. I have a windows computer if that has anything to do with this!

**Comment by marvinquiet** [comment]
This is an answer you can refer to: https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

**Comment by leahsidoniesmith** [comment]
follow up question: do we need transitivity? (implementation does not have transitivity, api does)

**Comment by lujiaying** [comment]
> follow up question: do we need transitivity? (implementation does not have transitivity, api does)

This is a good question. Transitivity is an advanced topic in software engineering, and highly related to Android. This really depends on what type of module you are building. 
For this course, and in short, `testImplementation` is preferable due to its characteristics. I highly recommend you to read further information in the link mentioned above.
