### ISSUE TITLE
[QZ# 3] MSD Radix Sort out of bounds error

### ISSUE THREAD

**Issue by leahsidoniesmith** [emory-courses/dsa-java#63]
I keep getting an out of bounds error even though I've checked my for-loops so many times...

If a TA could provide any guidance that would be a huge help! Thank you

Here is my code: https://github.com/leahsidoniesmith/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/distribution/RadixSortQuiz.java

**Comment by marvinquiet** [comment]
I do have a suggestion for printing out all your indexes and array length to find the error. I could not tell from the code but just try first printing out the length of your variable `a`, `count `, and `temp`. Whenever you used an index, print it out, and then you can find out where the error occurs. 

Or instead of printing, you can use debugging mode to track the error.
