### ISSUE TITLE
[QZ#3 Lambda Question] 

### ISSUE THREAD

**Issue by TFloyd1989** [emory-courses/dsa-java#65]
Where does the 'key' in the lambda function in LSD sort come from?(key -> (key / div) % 10). I don't see it initialized anywhere, I was wondering how its value is determined?

**Comment by TFloyd1989** [comment]
I actually took some time to understand it and I have a good grasp of it. Instead of the previous question, I now wonder what other sort we can use instead of bucketsort?

**Comment by marvinquiet** [comment]
For MSD, you can use the bucketsort. I still feel it reasonable to track the beginIndex and endIndex. 

For how to track, you can actually get the size of each bucket by using `buckets.get(digit).size()`, then a recursive way would be fine

**Comment by TFloyd1989** [comment]
Thank you, however, what does digit represent? The digit of the bucket such as 0?

**Comment by TFloyd1989** [comment]
Is there also a way to find the total number of buckets?

**Comment by marvinquiet** [comment]
Yes, digit represents 0-9. 

Yes, there is a way because `buckets` is just a list referring to line 31 [here](https://github.com/emory-courses/dsa-java/blob/master/src/main/java/edu/emory/cs/sort/distribution/BucketSort.java). Similarly, the way to get the number of buckets is the way of getting the length of the list. Does it sound reasonable?

**Comment by TFloyd1989** [comment]
I think this makes sense
